### ndarray 생성

#### array 함수

In [1]:
import numpy as np
arr1 = np.array([1, 2, 3])   # int로만 구성
arr2 = np.array([1, 2, 3.0]) # float 포함
arr3 = np.array([1, 2, "3"]) # str 포함

print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)

[1 2 3] int32
[1. 2. 3.] float64
['1' '2' '3'] <U11


In [2]:
arr1 = np.array([1, 2, 3])                             # 1차원
arr2 = np.array([[1, 2, 3], [4, 5, 6]])                # 2차원
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3차원

print(arr1.shape)                                      # arr1의 모양 출력
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(2, 2, 2)


#### arange와 linspace 함수

In [3]:
arr1 = np.arange(5)             # 0부터 5까지 1씩 증가
arr2 = np.arange(-1, 4.5, 1.5) # -1부터 4.5까지 1.5씩 증가 
arr3 = np.arange(10, 1, -1)    # 10부터 1까지 -1씩 증가
arr4 = np.linspace(0, 1, 11)   # 0부터 1까지 등간격의 10개의 요소 생성

print("np.arange(5):{}".format(arr1))
print("np.arange(-1, 4.5, 1.5):{}".format(arr2))
print("np.arange(10, 1, -1):{}".format(arr3))
print("np.linspace(0, 1, 10):{}".format(arr4))

np.arange(5):[0 1 2 3 4]
np.arange(-1, 4.5, 1.5):[-1.   0.5  2.   3.5]
np.arange(10, 1, -1):[10  9  8  7  6  5  4  3  2]
np.linspace(0, 1, 10):[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


#### zeros 함수

In [4]:
arr1 = np.zeros(5)                     # 크기: 5
arr2 = np.zeros((3, 2))                # 크기: (3, 2)
arr3 = np.zeros((2, 2), dtype = bool)  # 크기 (2,2), 자료형: bool

print(arr1)
print(arr2)
print(arr3)

[0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[False False]
 [False False]]


#### random 모듈

In [5]:
arr1 = np.random.random(5)
arr2 = np.random.random((2, 2))
print(arr1)
print(arr2)

[0.11746892 0.99682163 0.02619123 0.8515939  0.08800338]
[[0.07423996 0.05226403]
 [0.24045014 0.84789972]]


In [6]:
arr1 = np.random.normal(0, 1, 5)
arr2 = np.random.normal(10, 3, (3, 3))
print(arr1)
print(arr2)

[-0.42582893  1.749246   -1.0124479   1.50768872 -0.15650393]
[[15.08999552  7.86065018 10.13456256]
 [ 8.82034797 11.85905405  7.48068577]
 [ 8.09574252  6.78242407  7.69194114]]


### 배열 구조 변경: reshape 메서드

In [7]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1.reshape(3, 2))  #  (3, 2)로 구조 변경
print(arr2.reshape(-1, 2)) # 열 개수를 2개로 구조 변경
print(arr1.reshape(-1, 1)) # 열 개수를 1개로 구조 변경

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [8]:
arr2.reshape(4, 2)

ValueError: cannot reshape array of size 6 into shape (4,2)