In [1]:
import numpy as np
x = np.arange(15).reshape(5, 3)
display(x)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### 합계 함수와 axis 키워드

In [2]:
print(np.sum(x))
print(x.sum())

105
105


In [3]:
# 행 방향 계산
print(np.sum(x, axis = 0))
print(x.sum(axis = 0))

# 열 방향 계산
print(np.sum(x, axis = 1))
print(x.sum(axis = 1))

[30 35 40]
[30 35 40]
[ 3 12 21 30 39]
[ 3 12 21 30 39]


### 자주 사용하는 집계 함수

In [4]:
print("열별 합계: {}".format(np.sum(x, axis = 0)))
print("전체 합계: {}".format(np.sum(x)))
print("행별 최솟값: {}".format(x.min(axis = 1)))
print("행 방향 최솟값: {}".format(x.min(axis = 0)))
print("전체 최댓값: {}".format(x.max()))
print("열별 표준편차: {}".format(np.std(x, axis = 0)))
print("전체 중위수: {}".format(np.median(x)))
print("전체 상위 20%: {}".format(np.quantile(x, 0.2)))
print("유니크한 값 목록: {}".format(np.unique(x)))

열별 합계: [30 35 40]
전체 합계: 105
행별 최솟값: [ 0  3  6  9 12]
행 방향 최솟값: [0 1 2]
전체 최댓값: 14
열별 표준편차: [4.24264069 4.24264069 4.24264069]
전체 중위수: 7.0
전체 상위 20%: 2.8000000000000003
유니크한 값 목록: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
